import { Ionicons } from "@expo/vector-icons";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { COLORS } from "../../constants/theme";
import { useAppLabels } from "../../hooks/useAppLabels";
import { useAuth } from "../../providers/AuthProvider";
import { ApiError } from "../../services/api";
import { GroupCapacity,GroupDetail,GroupSummary,SaveGroup } from "../../services/groups";

export default function GroupsRoute(){const{copy}=useAppLabels();const{request,user}=useAuth();const router=useRouter();const client=useQueryClient();const[creating,setCreating]=useState(false);const[form,setForm]=useState<SaveGroup>({name:"",description:null});
const query=useQuery({enabled:!!user,queryKey:["groups",user?.email],queryFn:()=>request<GroupSummary[]>("/api/v1/groups")});
const capacity=useQuery({enabled:!!user,queryKey:["groups","capacity",user?.email],queryFn:()=>request<GroupCapacity>("/api/v1/groups/capacity")});
const mutation=useMutation({mutationFn:(value:SaveGroup)=>request<GroupDetail>("/api/v1/groups",{method:"POST",body:JSON.stringify(value)}),onSuccess:(group)=>{setCreating(false);setForm({name:"",description:null});void client.invalidateQueries({queryKey:["groups"]});router.push({pathname:"/group/[id]",params:{id:group.id}});}});const full=!!capacity.data&&capacity.data.used>=capacity.data.limit;const capacityError=mutation.error instanceof ApiError&&mutation.error.status===409;
return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.screen}><Text style={styles.title}>{copy.groups.title}</Text><Text style={styles.description}>{copy.groups.description}</Text>
{capacity.data&&<Text style={styles.capacity}>{copy.groups.capacity(capacity.data.used,capacity.data.limit)}</Text>}<Pressable accessibilityRole="button" disabled={full&&!creating} onPress={()=>setCreating(!creating)} style={[styles.create,full&&!creating&&styles.disabled]}><Ionicons color={COLORS.surface} name={creating?"close":"add"} size={18}/><Text style={styles.createText}>{creating?copy.groups.cancel:copy.groups.create}</Text></Pressable>
{creating&&<View style={styles.form}><Text style={styles.label}>{copy.groups.name}</Text><TextInput maxLength={40} onChangeText={name=>setForm({...form,name})} placeholder={copy.groups.namePlaceholder} style={styles.input} value={form.name}/><Text style={styles.label}>{copy.groups.groupDescription}</Text><TextInput maxLength={160} multiline onChangeText={description=>setForm({...form,description})} placeholder={copy.groups.descriptionPlaceholder} style={[styles.input,styles.multiline]} value={form.description??""}/><Pressable accessibilityRole="button" disabled={form.name.trim().length<3||mutation.isPending} onPress={()=>mutation.mutate(form)} style={[styles.save,(form.name.trim().length<3||mutation.isPending)&&styles.disabled]}><Text style={styles.saveText}>{mutation.isPending?copy.groups.saving:copy.groups.save}</Text></Pressable></View>}
{mutation.isError&&<Text accessibilityRole="alert" style={styles.error}>{capacityError?copy.groups.capacityReached:copy.groups.actionError}</Text>}
{query.isPending?<ActivityIndicator color={COLORS.blueDark} style={styles.loading}/>:query.isError?<Text accessibilityRole="alert" style={styles.error}>{copy.groups.loadError}</Text>:!query.data?.length?<Text style={styles.empty}>{copy.groups.empty}</Text>:query.data.map(group=><Pressable accessibilityRole="button" key={group.id} onPress={()=>router.push({pathname:"/group/[id]",params:{id:group.id}})} style={styles.card}><View style={styles.cardText}><Text style={styles.cardTitle}>{group.name}</Text>{group.description&&<Text style={styles.cardDescription}>{group.description}</Text>}<Text style={styles.meta}>{copy.groups.members(group.memberCount)} · {group.isOwner?copy.groups.owner:copy.groups.member}</Text></View><Ionicons color={COLORS.blueDark} name="chevron-forward" size={20}/></Pressable>)}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{backgroundColor:COLORS.background,flex:1},screen:{padding:24,paddingBottom:90},title:{color:COLORS.ink,fontSize:32,fontWeight:"900",marginTop:12},description:{color:COLORS.muted,fontSize:15,lineHeight:22,marginTop:8},capacity:{color:COLORS.blueDark,fontSize:13,fontWeight:"800",marginTop:12},create:{alignItems:"center",alignSelf:"flex-start",backgroundColor:COLORS.blueDark,borderRadius:14,flexDirection:"row",gap:7,marginVertical:20,paddingHorizontal:15,paddingVertical:12},createText:{color:COLORS.surface,fontWeight:"900"},form:{backgroundColor:COLORS.surface,borderColor:COLORS.border,borderRadius:18,borderWidth:1,marginBottom:20,padding:16},label:{color:COLORS.ink,fontSize:12,fontWeight:"800",marginBottom:6,marginTop:10},input:{borderColor:COLORS.border,borderRadius:12,borderWidth:1,color:COLORS.ink,minHeight:48,paddingHorizontal:13},multiline:{minHeight:82,paddingTop:12,textAlignVertical:"top"},save:{alignItems:"center",backgroundColor:COLORS.blueDark,borderRadius:12,marginTop:14,padding:13},saveText:{color:COLORS.surface,fontWeight:"900"},disabled:{opacity:.5},loading:{marginTop:30},empty:{color:COLORS.muted,fontSize:14,marginTop:24},error:{color:"#A33A61",fontSize:13,marginVertical:14},card:{alignItems:"center",backgroundColor:COLORS.surface,borderColor:COLORS.border,borderRadius:17,borderWidth:1,flexDirection:"row",gap:12,marginBottom:11,padding:16},cardText:{flex:1},cardTitle:{color:COLORS.ink,fontSize:17,fontWeight:"900"},cardDescription:{color:COLORS.muted,fontSize:13,lineHeight:18,marginTop:4},meta:{color:COLORS.blueDark,fontSize:12,fontWeight:"800",marginTop:8}});
