import { Ionicons } from "@expo/vector-icons";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams,useRouter } from "expo-router";
import { useEffect,useState } from "react";
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,Share,StyleSheet,Text,TextInput,View } from "react-native";
import * as Linking from "expo-linking";
import QRCode from "react-native-qrcode-svg";
import { COLORS } from "../../../constants/theme";
import { useAppLabels } from "../../../hooks/useAppLabels";
import { useAuth } from "../../../providers/AuthProvider";
import { availableFriends,GroupDetail,GroupInvite,SaveGroup } from "../../../services/groups";
import { SocialProfile } from "../../../services/social";

export default function GroupRoute(){const{id}=useLocalSearchParams<{id:string}>();const{copy,language}=useAppLabels();const{request,user}=useAuth();const router=useRouter();const client=useQueryClient();const[editing,setEditing]=useState(false);const[confirm,setConfirm]=useState<string|null>(null);const[invite,setInvite]=useState<GroupInvite|null>(null);const[form,setForm]=useState<SaveGroup>({name:"",description:null});const key=["groups","detail",id,user?.email];
const query=useQuery({enabled:!!user&&!!id,queryKey:key,queryFn:()=>request<GroupDetail>(`/api/v1/groups/${id}`)});const friends=useQuery({enabled:!!user&&!!query.data?.isOwner,queryKey:["social","friends",user?.email],queryFn:()=>request<SocialProfile[]>("/api/v1/friends")});useEffect(()=>{if(query.data)setForm({name:query.data.name,description:query.data.description});},[query.data]);
const mutation=useMutation({mutationFn:({path,method="DELETE",body}:{path:string;method?:string;body?:unknown})=>request<GroupDetail|void>(path,{method,body:body?JSON.stringify(body):undefined}),onSuccess:(value)=>{setConfirm(null);setEditing(false);if(value)client.setQueryData(key,value);void client.invalidateQueries({queryKey:["groups"]});}});const act=(path:string,method="DELETE",body?:unknown)=>mutation.mutate({path,method,body});
const createInvite=useMutation({mutationFn:()=>request<GroupInvite>(`/api/v1/groups/${id}/invite`,{method:"POST"}),onSuccess:setInvite});const revokeInvite=useMutation({mutationFn:()=>request<void>(`/api/v1/groups/${id}/invite`,{method:"DELETE"}),onSuccess:()=>setInvite(null)});const inviteUrl=invite?Linking.createURL(`invite/group/${invite.token}`):null;
if(query.isPending)return <SafeAreaView style={styles.safe}><ActivityIndicator color={COLORS.blueDark} style={styles.loading}/></SafeAreaView>;
if(query.isError||!query.data)return <SafeAreaView style={styles.safe}><Text accessibilityRole="alert" style={styles.error}>{copy.groups.loadError}</Text></SafeAreaView>;const group=query.data;const candidates=availableFriends(friends.data??[],group.members);
return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.screen}><Pressable accessibilityLabel={copy.accessibility.back} accessibilityRole="button" onPress={()=>router.back()} style={styles.back}><Ionicons color={COLORS.blueDark} name="arrow-back" size={22}/></Pressable>
{editing?<View><Text style={styles.label}>{copy.groups.name}</Text><TextInput maxLength={40} onChangeText={name=>setForm({...form,name})} style={styles.input} value={form.name}/><Text style={styles.label}>{copy.groups.groupDescription}</Text><TextInput maxLength={160} multiline onChangeText={description=>setForm({...form,description})} style={[styles.input,styles.multiline]} value={form.description??""}/><View style={styles.row}><Action label={copy.groups.cancel} onPress={()=>setEditing(false)}/><Action primary label={copy.groups.save} onPress={()=>act(`/api/v1/groups/${id}`,"PUT",form)}/></View></View>:<><Text style={styles.title}>{group.name}</Text>{group.description&&<Text style={styles.description}>{group.description}</Text>}{group.isOwner&&<Pressable onPress={()=>setEditing(true)}><Text style={styles.link}>{copy.groups.edit}</Text></Pressable>}</>}
<Text style={styles.section}>{copy.groups.members(group.members.length)}</Text>{group.members.map(member=><View key={member.userId} style={styles.card}><View style={styles.grow}><Text style={styles.name}>{member.displayName}</Text><Text style={styles.username}>@{member.username} · {member.role==="owner"?copy.groups.owner:copy.groups.member}</Text></View>{group.isOwner&&member.role!=="owner"&&<Action danger label={copy.groups.remove} onPress={()=>act(`/api/v1/groups/${id}/members/${member.userId}`)}/>}</View>)}
{group.isOwner&&<><Text style={styles.section}>{copy.groups.addFriends}</Text>{candidates.length===0?<Text style={styles.empty}>{copy.groups.noFriends}</Text>:candidates.map(friend=><View key={friend.userId} style={styles.card}><View style={styles.grow}><Text style={styles.name}>{friend.displayName}</Text><Text style={styles.username}>@{friend.username}</Text></View><Action primary label={copy.friends.add} onPress={()=>act(`/api/v1/groups/${id}/members`,"POST",{userId:friend.userId})}/></View>)}</>}
{group.isOwner&&<View style={styles.inviteBox}><Text style={styles.section}>{copy.groups.invite}</Text><Text style={styles.empty}>{copy.groups.inviteDescription}</Text>{invite&&inviteUrl?<><View style={styles.qr}><QRCode value={inviteUrl} size={180}/></View><Text selectable style={styles.inviteUrl}>{inviteUrl}</Text><Text style={styles.empty}>{copy.groups.inviteExpires(new Intl.DateTimeFormat(language,{dateStyle:"medium"}).format(new Date(invite.expiresAt)))}</Text><View style={styles.row}><Action primary label={copy.groups.shareInvite} onPress={()=>void Share.share({message:inviteUrl})}/><Action danger label={copy.groups.revokeInvite} onPress={()=>revokeInvite.mutate()}/></View></>:<Action primary label={createInvite.isPending?copy.groups.generatingInvite:copy.groups.generateInvite} onPress={()=>createInvite.mutate()}/>}</View>}
<View style={styles.footer}>{group.isOwner?<Action danger label={confirm==="delete"?copy.groups.confirm:copy.groups.delete} onPress={()=>confirm==="delete"?mutation.mutate({path:`/api/v1/groups/${id}`},{onSuccess:()=>router.replace("/groups")}):setConfirm("delete")}/>:<Action danger label={confirm==="leave"?copy.groups.confirm:copy.groups.leave} onPress={()=>confirm==="leave"?mutation.mutate({path:`/api/v1/groups/${id}/membership`},{onSuccess:()=>router.replace("/groups")}):setConfirm("leave")}/>}</View>{mutation.isError&&<Text accessibilityRole="alert" style={styles.error}>{copy.groups.actionError}</Text>}</ScrollView></SafeAreaView>}
function Action({label,onPress,primary,danger}:{label:string;onPress:()=>void;primary?:boolean;danger?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.action,primary&&styles.primary,danger&&styles.danger]}><Text style={[styles.actionText,(primary||danger)&&styles.actionTextLight]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({safe:{backgroundColor:COLORS.background,flex:1},screen:{padding:24,paddingBottom:90},loading:{marginTop:60},back:{alignItems:"center",height:44,justifyContent:"center",width:44},title:{color:COLORS.ink,fontSize:30,fontWeight:"900",marginTop:14},description:{color:COLORS.muted,fontSize:15,lineHeight:22,marginTop:7},link:{color:COLORS.blueDark,fontWeight:"800",marginTop:12},section:{color:COLORS.ink,fontSize:12,fontWeight:"900",marginBottom:9,marginTop:26},card:{alignItems:"center",backgroundColor:COLORS.surface,borderColor:COLORS.border,borderRadius:15,borderWidth:1,flexDirection:"row",gap:10,marginBottom:9,padding:14},grow:{flex:1},name:{color:COLORS.ink,fontSize:15,fontWeight:"800"},username:{color:COLORS.muted,fontSize:12,marginTop:3},empty:{color:COLORS.muted,fontSize:13},label:{color:COLORS.ink,fontSize:12,fontWeight:"800",marginBottom:6,marginTop:14},input:{backgroundColor:COLORS.surface,borderColor:COLORS.border,borderRadius:12,borderWidth:1,color:COLORS.ink,minHeight:48,paddingHorizontal:13},multiline:{minHeight:82,paddingTop:12,textAlignVertical:"top"},row:{flexDirection:"row",flexWrap:"wrap",gap:10,justifyContent:"flex-end",marginTop:12},action:{borderColor:COLORS.border,borderRadius:10,borderWidth:1,paddingHorizontal:12,paddingVertical:9},primary:{backgroundColor:COLORS.blueDark,borderColor:COLORS.blueDark},danger:{backgroundColor:"#A33A61",borderColor:"#A33A61"},actionText:{color:COLORS.ink,fontSize:12,fontWeight:"800"},actionTextLight:{color:COLORS.surface},inviteBox:{backgroundColor:COLORS.surface,borderColor:COLORS.border,borderRadius:16,borderWidth:1,marginTop:24,padding:16},qr:{alignItems:"center",marginVertical:18},inviteUrl:{color:COLORS.blueDark,fontSize:12,lineHeight:18},footer:{alignItems:"flex-start",marginTop:28},error:{color:"#A33A61",fontSize:13,margin:24}});
